name: github-docker

on: 
  push: 
    branches:
      - 'docker*'
      - 'master'

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v4
        with:
          context: ./contrib/docker/
          cache-from: type=registry,ref=dealii/dependencies:focal
          cache-to: type=inline
          push: ${{github.ref_name == 'master'}}
          tags: dealii/dealii:master-focal

      - name: Build and push Docker image of master with root user
        uses: docker/build-push-action@v4
        with:
          context: ./contrib/docker/
          file: ./contrib/docker/Dockerfile.root
          cache-from: type=registry,ref=dealii/dealii:master-focal
          cache-to: type=inline
          push: ${{github.ref_name == 'master'}}
          tags: dealii/dealii:master-focal-root

